/**
 * Created by Raphael Karanja on 2019-01-25.
 */

//COURSES
export const CREATE_COURSES_SUCCESS = 'CREATE_COURSES_SUCCESS';
export const UPDATE_COURSES_SUCCESS = 'UPDATE_COURSES_SUCCESS';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';

//CATEGORIES
export const LOAD_CATEGORY_SUCCESS = 'LOAD_CATEGORY_SUCCESS';

//AUTHORS
export const CREATE_AUTHOR = 'CREATE_AUTHOR';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';