/**
 * Created by Raphael Karanja on 2019-01-25.
 */

//COURSES
export const CREATE_COURSE = 'CREATE_COURSE';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';

//AUTHORS
export const CREATE_AUTHOR = 'CREATE_AUTHOR';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';